import subprocess
import os
from datetime import datetime
import sys

def generate_report(topic):
    """
    Generates a medical report on the given topic using an LLM.

    Args:
        topic: The medical topic to generate a report on.

    Returns:
        The report generated by the LLM.
    """
    try:
        with open("prompts/reporter.txt", "r") as f:
            prompt_template = f.read()
    except FileNotFoundError:
        return "Error: prompts/reporter.txt not found."

    prompt = prompt_template.format(topic=topic)


    # Use the llm command-line tool to interact with the model
    command = ["llm", "-m", "gemini-exp-1206", prompt]
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    stdout, stderr = process.communicate()

    if stderr:
        return f"Error during LLM execution:\n{stderr}"

    report = stdout.strip()

    # Create subdirectory if it doesn't exist
    subdirectory = os.path.join("reports", "".join(c if c.isalnum() else "_" for c in topic).strip("_"))
    os.makedirs(subdirectory, exist_ok=True)

    now = datetime.now()
    date_time = now.strftime("%Y%m%d%H%M%S")
    filename = f"{subdirectory}/report{date_time}.md"
    with open(filename, "w") as f:
        f.write(report)
    
    return report


if __name__ == "__main__":
    
    if len(sys.argv) > 1:
        topic = sys.argv[1]
    else:
        print("Error: No topic provided.")
        sys.exit(1)
    report = generate_report(topic)
    print(report)